name: Open Homebrew PR

on:
  repository_dispatch:
    types:
      - stable-release

jobs:

  bump-formula:

    name: Bump formula
    runs-on: ubuntu-20.04

    steps:

      - name: Dump GitHub context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
